index mobile
zeckson/htmlacademy-pink pull request #1
Opened 2020-06-21 14:23 UTC by KirillGrant

2020-06-21 17:44 UTC, zeckson requested changes
Очень круто! Всего пару моментов поправить)

2020-06-21 17:44 UTC, zeckson commented on index.html
> +<html lang="en">
Неправильный язык задан

2020-06-21 17:44 UTC, zeckson commented on index.html
> +  <div class="header__presentation">
Что, если мы уберём этот блок? Т.е. вместо двух вложенных блоков сделаем один.

2020-06-21 17:44 UTC, zeckson commented on index.html
> +    <div class="reviews__btn-list">
Написано список, а это не список, лучше назвать `reviews__controls` или `reviews__buttons`

2020-06-21 17:44 UTC, zeckson commented on index.html
> +  <div class="decorate-block"></div>
Это не нужно, это можно сделать при помощи `:: before, ::after`

2020-06-21 17:44 UTC, zeckson commented on index.html
> +  <div class="offer__btn-list">
`offer__controls` лучше описывает, т.к. это всё-таки не список

2020-06-21 23:43 UTC, KirillGrant commented on index.html
> +<html lang="en">
ru?

2020-06-21 23:48 UTC, KirillGrant commented on index.html
> +  <div class="header__presentation">
согласен

2020-06-21 23:50 UTC, KirillGrant commented on index.html
> +    <div class="reviews__btn-list">
fix

2020-06-21 23:51 UTC, KirillGrant commented on index.html
> +  <div class="decorate-block"></div>
fix

2020-06-21 23:51 UTC, KirillGrant commented on index.html
> +  <div class="offer__btn-list">
fix

2020-06-22 10:33 UTC, zeckson commented on index.html
> +<html lang="en">
да

2020-07-30 15:29 UTC, zeckson approved these changes
Да, круто!
Давай дальше!

2020-07-30 15:29 UTC, merged