#6/5. #6/6
zeckson/htmlacademy-pink pull request #3
Opened 2020-07-31 13:10 UTC by KirillGrant

2020-07-31 13:21 UTC, zeckson requested changes
Нет блока `btn`, значит и файл `sass/btn.scss` не нужен

2020-07-31 13:21 UTC, zeckson commented on gulpfile.js
> +  return gulp.src('sass/**/*.+(scss|sass)')
Исправил с работающей сборки на неработающую =(
Что ты хотел этим сделать?

2020-07-31 13:21 UTC, zeckson commented on index.html
> +    <button class="popup-btn" type="button"><img src="http://placehold.it/50x24"></button>
Кажется я проглядел это имя класса =(
Если ты хочешь чтобы кнопки имели общий стиль, то тогда тебе нужно использвать блок `button`.
Давай назовём стиль кнопки `button`, т.к. кнопка имеет отдельный стиль. Или если это специальная кнопка заголовка, то тогда это `header__popup-button`

2020-07-31 13:32 UTC, zeckson requested changes
Файлы `woff` и `readme.md` надо вернуть.
Давай не будем создавать пустые файлы.
Если файл есть, то в нём должно что-то быть, иначе этот файл надо удалить.

2020-07-31 13:32 UTC, zeckson commented on sass/body.scss
> +  src: url(../fonts/opensans.woff2);
не хватает кавычек
Смотри пример тут — https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face

2020-08-01 12:37 UTC, zeckson requested changes
Очень круто, сделал больше чем требуется по заданию, красавчик!
Но не обошлось и без странностей — откуда-то появилось очень много левых стилей которые не используются.
Также убежал элемент `offer__controls` из блока `offer` в `index.html` — это мы проглядели в прошлый раз. 
Надо поправить.
На все замечания пожалуйста как-нибудь отреагируй — или ответь, или хотя бы эмодзи поставь.
Удачи!

2020-08-01 12:37 UTC, zeckson commented on sass/README
> +Папка для шрифтов.
переименовать в `readme.md` или удалить

2020-08-01 12:37 UTC, zeckson commented on sass/main.scss
> +  border: gold 5px solid;
Если ты хочешь выделить блок, то лучше использовать `outline` вместо `border`, в отличие от `border` — `outline` не добавляет ширины блоку.
http://gearmobile.github.io/css/css-outline-border/

2020-08-01 12:37 UTC, zeckson commented on sass/main.scss
> +    margin-top: 0;
Маргины лучше группировать рядом, чтобы они сразу все были видны.
Плюс я бы порекомендовал придумать удобную группировку, например:
Было:
```css
  h2 {
    display: inline-block;
    text-align: center;
    margin-left: auto;
    margin-right: auto;
    font-size: $font-24;
    font-weight: lighter;
    margin-top: 0;
    margin-bottom: 0;
    line-height: 24px;
  }
```
стало:
```css
  h2 {
    // Рамки границы, позиционирование
    display: inline-block;
    margin-left: auto;
    margin-right: auto;
    margin-top: 0;
    margin-bottom: 0;

    // Внешний вид (цвета, шрифты)
    text-align: center;
    font-size: $font-24;
    font-weight: lighter;
    line-height: 24px;
  }
```

2020-08-01 12:37 UTC, zeckson commented on sass/main.scss
> +    display: inline-block;
Зачем `inline-block`?

2020-08-01 12:37 UTC, zeckson commented on sass/main.scss
> +    font-size: $font-24;
Наследуемые параметры текста для общих блоков нужно вынести в общие css-правила, т.к. h2 на странице везде выглядят одинаково:
```css
h2 {
    font-size: $font-24;
    font-weight: lighter;
    line-height: 24px;
}
```
Общие правила из базового курса здесь сохраняются.
Далее я буду называть эти места `Выделить в общий стиль`

2020-08-01 12:37 UTC, zeckson commented on sass/main.scss
> +.main__iphone--img {
Кажется этот класс нигде не используется.
Удалить

2020-08-01 12:37 UTC, zeckson commented on sass/header.scss
> +  }
Форматирование поехало (

2020-08-01 12:37 UTC, zeckson commented on sass/presentation.scss
> +    font-size: $font-14;
Выделить в общий стиль

2020-08-01 12:37 UTC, zeckson commented on sass/presentation.scss
> +  display: flex;
Почему `flex`?

2020-08-01 12:37 UTC, zeckson commented on sass/presentation.scss
> +  justify-content: center;
Я бы прописал: `justify-content: space-evenly;`
И убрал бы нафиг странные паддинги:
```css
  li:nth-child(1) {
    padding-right: 37px;
  }

  li:nth-child(2) {
    padding-right: 37px;
  }
```
Выглядит одинаково, а кода меньше

2020-08-01 12:37 UTC, zeckson commented on sass/about.scss
> +  width: 320px;
Здесь уже не нужна ширина, т.к. она задана в родителе

2020-08-01 12:37 UTC, zeckson commented on sass/about.scss
> +  margin: 0 auto;
И центрирование здесь не нужно

2020-08-01 12:37 UTC, zeckson commented on sass/about.scss
> +    padding-left: 20px;
Чтобы не повторять одни и те же паддинги в детях, его можно просто вынести в родителя в `.about__text`

2020-08-01 12:37 UTC, zeckson commented on sass/about.scss
> +    width: 280px;
Зачем ширина?

2020-08-01 12:37 UTC, zeckson commented on sass/about.scss
> +    display: inline-block;
Почему `inline-block`?

2020-08-01 12:37 UTC, zeckson commented on sass/about.scss
> +.about__text--third {
Класс не используется

2020-08-01 12:37 UTC, zeckson commented on sass/body.scss
> +  src: url("../fonts/opensanslight.woff");
Шрифты перезаписывают друг друга, чтобы правильно подключить шрифты с разными версиями, нужно использовать следующий синтаксис:
```
  src: url("../fonts/opensans.woff") format("woff"),
  url("../fonts/opensans.woff2") format("woff2");
```
Смотри https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face

2020-08-01 12:37 UTC, zeckson commented on sass/contact.scss
> +    font-size: $font-24;
Выделить в общий стиль

2020-08-01 12:37 UTC, zeckson commented on sass/reviews.scss
> +  border: gold 5px solid;
`outline`

2020-08-01 12:37 UTC, zeckson commented on sass/offer.scss
> +    background-image: url("../img/");
Сломанный урл (

2020-08-01 12:37 UTC, zeckson commented on sass/offer.scss
> +  background-image: url("../img/");
Сломанный урл (

2020-08-01 12:37 UTC, zeckson commented on sass/offer.scss
> +  background-image: url("../img/");
Сломанный урл (

2020-08-01 12:37 UTC, zeckson commented on sass/contact.scss
> +  width: 280px;
У тебя очень много блоко имеют одну и ту же мантру:
```css
    width: 280px;
    padding-right: 20px;
    padding-left: 20px;
    margin: 0 auto;
```
Это означает, что этот код можно смело перенести в родителя и 6 блоков станут на 4 строки короче

2020-08-01 12:37 UTC, zeckson commented on sass/contact.scss
> +.contact__mini-title {
Стиль не используется. 
Откуда вообще так много неиспользуемых стилей?!

2020-08-01 12:37 UTC, zeckson commented on sass/contact.scss
> +    padding-left: 60px;
Лучше использовать выравнивание для текста: `text-align: center;` иначе вёрстка начнёт ехать, если надпись изменится.

2020-08-01 12:37 UTC, zeckson commented on sass/map.scss
> +  border: gold 5px solid;
`outline`

2020-08-03 14:57 UTC, KirillGrant commented on gulpfile.js
> +  return gulp.src('sass/**/*.+(scss|sass)')
затупил

2020-08-03 14:57 UTC, KirillGrant commented on index.html
> +    <button class="popup-btn" type="button"><img src="http://placehold.it/50x24"></button>
исправил

2020-08-03 14:57 UTC, KirillGrant commented on sass/body.scss
> +  src: url(../fonts/opensans.woff2);
исправил

2020-08-03 14:58 UTC, KirillGrant commented on sass/README
> +Папка для шрифтов.
удалил

2020-08-03 14:59 UTC, KirillGrant commented on sass/main.scss
> +  border: gold 5px solid;
понял

2020-08-03 14:59 UTC, KirillGrant commented on sass/main.scss
> +    margin-top: 0;
понял, постараюсь придерживаться

2020-08-03 15:00 UTC, KirillGrant commented on sass/offer.scss
> +  background-image: url("../img/");
чуть позже будут картинки

2020-08-03 15:00 UTC, KirillGrant commented on sass/contact.scss
> +.contact__mini-title {
исправил

2020-08-03 15:01 UTC, KirillGrant commented on sass/map.scss
> +  border: gold 5px solid;
ок

2020-08-03 15:16 UTC, zeckson commented on sass/body.scss
> +  src: url(../fonts/opensans.woff2);
отправь исправления

2020-08-03 15:19 UTC, zeckson commented on sass/offer.scss
> +  background-image: url("../img/");
не надо делать заготовок на будущее, так мне сложнее проверить, что сделано, а что нет и почему
Должно быть только то, что нужно

2020-08-05 14:20 UTC, KirillGrant commented on sass/main.scss
> +.main__iphone--img {
удалил

2020-08-05 15:03 UTC, KirillGrant commented on sass/header.scss
> +  }
форматирование? что это такое?

2020-08-05 15:06 UTC, KirillGrant commented on sass/presentation.scss
> +  display: flex;
удобно выравнивать

2020-08-05 15:10 UTC, KirillGrant commented on sass/about.scss
> +  margin: 0 auto;
попробовал убрать ширину и маргин- поехала верстка

2020-08-05 15:11 UTC, KirillGrant commented on sass/about.scss
> +  width: 320px;
едет верстка без него

2020-08-05 15:14 UTC, zeckson commented on sass/presentation.scss
> +  display: flex;
а что ты тут собственно выравниваешь? Это же кнопка, а не сетка.

2020-08-05 15:15 UTC, KirillGrant commented on sass/about.scss
> +    padding-left: 20px;
не увидел падинга в коде

2020-08-05 15:16 UTC, KirillGrant commented on sass/about.scss
> +    width: 280px;
для центровки

2020-08-05 15:16 UTC, KirillGrant commented on sass/about.scss
> +    display: inline-block;
для центровки удобной

2020-08-05 15:17 UTC, KirillGrant commented on sass/about.scss
> +.about__text--third {
удалил

2020-08-05 15:19 UTC, KirillGrant commented on sass/body.scss
> +  src: url("../fonts/opensanslight.woff");
исправил

2020-08-05 15:19 UTC, KirillGrant commented on sass/reviews.scss
> +  border: gold 5px solid;
ок

2020-08-05 15:20 UTC, KirillGrant commented on sass/offer.scss
> +    background-image: url("../img/");
знаю, жду когда можно будет вставить картинки  в проект

2020-08-05 15:21 UTC, KirillGrant commented on sass/offer.scss
> +  background-image: url("../img/");
жду когда можно вставить в проект картинки

2020-08-05 15:21 UTC, KirillGrant commented on sass/offer.scss
> +  background-image: url("../img/");
понял, сейчас потру

2020-08-05 15:21 UTC, KirillGrant commented on sass/offer.scss
> +  background-image: url("../img/");
понял потру

2020-08-05 15:21 UTC, KirillGrant commented on sass/offer.scss
> +    background-image: url("../img/");
понял потру

2020-08-05 15:30 UTC, zeckson commented on sass/about.scss
> +    display: inline-block;
так а где центровка? я не вижу?

2020-08-05 16:08 UTC, zeckson commented on sass/header.scss
> +  }
файл изменился и комментарий уже нерелевантен(

2020-08-05 16:14 UTC, zeckson commented on sass/README
> +Папка для шрифтов.
не удалено

2020-08-05 16:15 UTC, zeckson commented on sass/body.scss
> +  src: url("../fonts/opensanslight.woff");
не исправлено(

2020-08-05 16:16 UTC, zeckson commented on sass/contact.scss
> +.contact__mini-title {
не исправлено

2020-08-05 16:16 UTC, zeckson commented on sass/main.scss
> +  border: gold 5px solid;
не исправлено

2020-08-10 12:51 UTC, zeckson requested changes
Многие проблемы так и остались без внимания, можно их пропустить, но они потом будут больно тебя догонять, предлагаю подумать над следующими вещами:
- одинаковые элементы задаются по месту, вместо того чтобы выделить в один общий стиль, например, `h1`, `h2`, `a` и т.д.
- лишние правила, например, `flex` — там где нет никакой сетки, `inline-block` — там где он просто не нужен
- странные выравнивания `padding-left: 40px` вместо `text-align: center`
Можно двигаться дальше, напиши, пожалуйста под всеми замечаниями, будешь ли ты их исправлять или нет.

2020-08-10 12:51 UTC, zeckson commented on sass/body.scss
> +@font-face {
Шрифты всё ещё перезаписывают друг друга. Вот [здесь](https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face) можно посмотреть пример того как подключить шрифт и указать для него разные типы и версии.
Должно получится что-то вроде:
```
@font-face {
  font-family: "Open Sans";
  src: url("../fonts/opensanslight.woff2") format("woff2"),
       url("../fonts/opensanslight.woff") format("woff");
}
```
Два `@font-face` с одинаковым именем будут просто затирать друг друга

2020-08-11 12:46 UTC, KirillGrant reviewed
comments

2020-08-11 12:46 UTC, KirillGrant commented on sass/about.scss
> +    display: inline-block;
h3 {
    display: inline-block;
    text-align: center;
  }нет разве ?

2020-08-11 12:46 UTC, KirillGrant commented on sass/body.scss
> +@font-face {
сделано

2020-08-11 12:46 UTC, KirillGrant commented on sass/contact.scss
> +    padding-left: 60px;
исправлено

2020-08-11 12:46 UTC, KirillGrant commented on sass/contact.scss
> +  width: 280px;
посмотрю по ходу следующего задания

2020-08-11 12:46 UTC, KirillGrant commented on sass/contact.scss
> +    font-size: $font-24;
пересмотрел код и не понял зачем ?

2020-08-11 12:52 UTC, zeckson commented on sass/about.scss
> +    display: inline-block;
Если убрать `inline-block` что изменится?

2020-08-11 12:55 UTC, zeckson commented on sass/contact.scss
> +    font-size: $font-24;
Потому что h1, h2, h3 и т.д. одинаковые на всех страницах. Не нужно писать что раз одно и тоже, вместо этого можно задать один стиль и его использовать

2020-08-11 12:57 UTC, zeckson reviewed
Не вижу коммитов(

2020-08-12 15:02 UTC, merged